name: Bug 反馈（使用中文）
description: 界面异常、配置错误、连接错误等
labels: ['bug']
body:
  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 尽可能详细描述你的问题
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志文件
      description: |
        可以上传 `C:\Users\<你的用户名>\AppData\Roaming\maa-x\logs` 中相关 log 文件，以帮助我们排查问题
        注：log 文件内可能包含了你电脑的所有进程信息，请考虑是否上传
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗？
      description: |
        使用的模拟器？操作系统？相关的配置？链接？参考资料？
        任何能让我们对你所遇到的问题有更多了解的东西
    validations:
      required: false
