name: Bug Report (in English)
description: >-
  UI errors, configuration errors, connection errors, etc.
labels: ['bug']
body:
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Describe your problem in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: >-
        You can upload log files in `C:\Users\<your username>\AppData\Roaming\maa-x\logs` to help us troubleshoot.
        Note: The log file may contain all the process information of your computer, please consider whether to upload it.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Anthing else?
      description: >-
        Emulator used, operating system, related configuration, links,
        reference material, etc.

        Anything that will give us more insight into the problem
        you are having.
    validations:
      required: false
