name: "Build/PullRequest"

on:
  pull_request:
    branches: 
    - main
    - dev
    paths-ignore:
    - "**.md"
    - "**.spec.js"
    - ".idea"
    - ".vscode"
    - ".dockerignore"
    - "Dockerfile"
    - ".gitignore"
    - ".github/**"
    - "!.github/workflows/*.yml"

defaults:
  run:
    shell: "bash"

jobs:
  release:
    # see more environment https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: ["amd64", "arm64"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Write config to npmrc(Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: echo -e "\nnode-linker = hoisted\nshamefully-hoist = true" >> $HOME/.npmrc

      - name: Write config to npmrc(Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: echo  "`nnode-linker = hoisted`nshamefully-hoist = true" >> $env:USERPROFILE/.npmrc

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
      
      # https://github.com/marketplace/actions/electron-builder-action
      - name: Compile Electron app
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: release/*/*.zip
      
