name: "Build/Release"

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/release.yml"

defaults:
  run:
    shell: "bash"

jobs:
  release:
    # see more environment https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node: ["16"]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Check pre-release
        uses: actions-ecosystem/action-regex-match@v2
        id: pre-release
        with:
          text: ${{ github.ref_name }}
          regex: '(alpha)|(beta)|(rc)'

      - name: Create Draft Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ steps.pre-release.outputs.match != '' }}
          draft: true
          automatic_release_tag: ${{ github.ref_name }}

      # https://github.com/marketplace/actions/electron-builder-action
      - name: Compile & Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: prebuild
          args: --config electron-builder.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' && needs.get_metadata.outputs.branch == 'main'}}
          max_attempts: 5
      
