name: "Build/Release"

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/release.yml"

defaults:
  run:
    shell: "bash"

jobs:
  release:
    # see more environment https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ${{ matrix.goos }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: "--max_old_space_size=4096"


    strategy:
      matrix:
        node: ["18"]
        goos: [windows-latest, ubuntu-latest]
        goarch: ["amd64"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: Check pre-release
        uses: actions-ecosystem/action-regex-match@v2
        id: pre-release
        with:
          text: ${{ github.ref_name }}
          regex: '(alpha)|(beta)|(rc)'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: ${{ steps.pre-release.outputs.match != '' }}
          draft: true

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # https://github.com/marketplace/actions/electron-builder-action
      - name: Compile & Release Electron app
        uses: MaaAssistantArknights/action-electron-builder@v1.7.0
        with:
          build_script_name: prebuild # the script(npm run prebuild) run before electron-builder
          skip_install: "true"
          args: --config electron-builder.json
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' && needs.get_metadata.outputs.branch == 'main'}}
          max_attempts: 5
      
